Fixed the issue with building the image
I fixed 2 issues that were causing errors when building the image:

1. I changed the way we check to see if an image already exists on the user's machine. I was initially using 'inspect' which was resulting in an error whenever the image couldn't be found. I am now using 'docker images -q' to see if the image exists based on it's ID. This solved the "Error building Docker image: Error: Command failed: docker inspect --format='{{.Created}}' dig
Error: No such object: dig " error.

2. My buildImage function was not running the build command from inside the dig repository which was leading to an issue accessing the Dockerfile. I fixed the path and the issue is solved.